import { Box, CircularProgress, Grid, Stack, Typography } from '@mui/material';
import useAxios from 'axios-hooks';
import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';

import MainLayout from '../containers/layouts/main';
import ServicesItem from '../containers/main/ServicesItem';
import CategoryItem from '../containers/main/СategoryItem';

const Home: NextPage = () => {
  const [homeStore, setHomeStore] = useState([]);
  const [currentPageStore, setCurrentPageStore] = useState(1);
  const [lastPage, setLastPage] = useState<number>(2);
  const [fetching, setFetching] = useState<boolean>(true);
  const [homeServices] = useAxios(`/store/home-services`);

  const [{ loading }, getHomeStore] = useAxios(`/store/catalogs/home?page=${currentPageStore}`, { manual: true });

  useEffect(() => {
    if (fetching && lastPage + 1 > currentPageStore) {
      getHomeStore()
        .then(({ data }) => {
          setHomeStore([...homeStore, ...data.data]);
          setLastPage(data.meta.lastPage);
          setCurrentPageStore((prevState) => prevState + 1);
        })
        .finally(() => setFetching(false));
    }
  }, [fetching]);

  useEffect(() => {
    document.addEventListener('scroll', scrollHandler);

    return function () {
      document.removeEventListener('scroll', scrollHandler);
    };
  }, []);

  const scrollHandler = (e) => {
    if (e.target.documentElement.scrollHeight - (e.target.documentElement.scrollTop + window.innerHeight) < 150) {
      setFetching(true);
    }
  };

  return (
    <div>
      <Head>
        <title>Проект МОСТ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon.png" />
      </Head>

      <MainLayout>
        <Grid container rowSpacing={7}>
          <Grid item xs={12}>
            <Grid container rowSpacing={2}>
              <Grid item xs={12}>
                <Typography component="h1" fontSize={26} fontWeight={700} fontFamily={'Raleway'}>
                  Сервисы Most
                </Typography>
              </Grid>
              <Grid item xs={12}>
                {homeServices.loading ? [] : <ServicesItem servicesData={homeServices.data}></ServicesItem>}
              </Grid>
            </Grid>
          </Grid>

          <Grid item xs={12}>
            <Stack spacing={2}>
              <CategoryItem data={homeStore} loading={loading} />
              <Box textAlign="center">{loading && homeStore.length > 1 && <CircularProgress color="secondary" />}</Box>
            </Stack>
          </Grid>
        </Grid>
      </MainLayout>
    </div>
  );
};

export default Home;
